// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm1jKOH6hpaRi6UAVG94Hee7EItnIjQFY',
    appId: '1:344791553497:web:436bd22f9c2e1e4a2eb5c8',
    messagingSenderId: '344791553497',
    projectId: 'foodmate-7c3df',
    authDomain: 'foodmate-7c3df.firebaseapp.com',
    storageBucket: 'foodmate-7c3df.appspot.com',
    measurementId: 'G-5JTGL51ZN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwj20I5t3EGcPGiN0ouDIMVM9RA-Ywxmk',
    appId: '1:344791553497:android:64305eadca16f0c12eb5c8',
    messagingSenderId: '344791553497',
    projectId: 'foodmate-7c3df',
    storageBucket: 'foodmate-7c3df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUGyaEfxI21AG0iJJvR0RtljvRe9__7c8',
    appId: '1:344791553497:ios:ed1edb17141e52e02eb5c8',
    messagingSenderId: '344791553497',
    projectId: 'foodmate-7c3df',
    storageBucket: 'foodmate-7c3df.appspot.com',
    iosClientId: '344791553497-l7l2v29eivmq2l501heajip7619chktk.apps.googleusercontent.com',
    iosBundleId: 'com.fawazalrasyid.foodmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUGyaEfxI21AG0iJJvR0RtljvRe9__7c8',
    appId: '1:344791553497:ios:ed1edb17141e52e02eb5c8',
    messagingSenderId: '344791553497',
    projectId: 'foodmate-7c3df',
    storageBucket: 'foodmate-7c3df.appspot.com',
    iosClientId: '344791553497-l7l2v29eivmq2l501heajip7619chktk.apps.googleusercontent.com',
    iosBundleId: 'com.fawazalrasyid.foodmate',
  );
}
